apiVersion: v1 
kind: PersistentVolume
metadata:
  name: pv-volume-ubuntu
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/vm/images/ubuntu22"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linuxbootdisk
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu22-pvc-ssh
  namespace: default
spec:
  ports:
    - name: ubuntu22-pvc-ssh
      protocol: TCP
      port: 22
      targetPort: 22
  selector:
    kubevirt.io/name: ubuntu22-pvc
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: vm-rdp
  namespace: default
spec:
  ports:
    - port: 3389
      name: rdp
      protocol: TCP
      targetPort: 3389
  selector:
    kubevirt.io/name: ubuntu22-pvc
  externalTrafficPolicy: Cluster
  type: LoadBalancer

---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu22-pvc
  namespace: default
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/name: ubuntu22-pvc
    spec:
      domain:
        cpu:
          cores: 4
          model: host-passthrough
        memory:
          guest: "4G"
        devices:
          # autoattachGraphicsDevice: true
          gpus:
          - name: igpu
            deviceName: intel.com/sriov-gpudevice
          disks:
          - name: bootdisk
            bootOrder: 1
            disk:
              bus: virtio
          autoattachPodInterface: true
          interfaces:
          - name: default
            masquerade: {}
        machine:
          type: q35
        firmware:
          bootloader:
            efi:
              secureBoot: false
      terminationGracePeriodSeconds: 0
      networks:
      - name: default
        pod: {}
      volumes:
      - name: bootdisk
        persistentVolumeClaim:
          claimName: linuxbootdisk
