apiVersion: v1
kind: Service
metadata:
  name: rdp
  namespace: default
spec:
  ports:
    - port: 3389
      name: rdp
      protocol: TCP
      targetPort: 3389
  selector:
    app/name: virtual-machine
  externalTrafficPolicy: Cluster
  type: LoadBalancer
