apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/pv-pvc
  - ../../components/ssh
namespace: default
namePrefix: ubuntu22-
commonLabels:
  app/name: ubuntu22-virtual-machine
patchesStrategicMerge:
  - pv_hostpath.yaml
  - vm_disks_volumes.yaml
patchesJson6902:
  - path: vm_label.yaml
    target:
      group: kubevirt.io
      version: v1      
      kind: VirtualMachine
      name: vm
