apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm
spec:
  template:
    spec:
      domain:
        devices:
          disks:
          - name: bootdisk
            bootOrder: 1
            disk:
              bus: virtio
          - name: cdromiso
            bootOrder: 2
            cdrom:
              bus: sata
              readonly: false
      volumes:
      - name: bootdisk
        persistentVolumeClaim:
          claimName: ubuntu22-bootdisk
      - name: cdromiso
        containerDisk:
          image: docker.io/rahulunair/ubvm22:v0.1
          imagePullPolicy: IfNotPresent
