apiVersion: v1 
kind: PersistentVolume
metadata:
  name: pv-volume-ubuntu
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/vm/images/ubuntu22"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linuxbootdisk
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: Service
metadata:
  name: vm-ubuntu-ssh
  namespace: default
spec:
  ports:
    - name: vm-ubuntu-ssh
      protocol: TCP
      port: 22
      targetPort: 22
  selector:
    kubevirt.io/name: vm-pvc-ubuntu
  type: NodePort

---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-pvc-ubuntu
  namespace: default
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/name: vm-pvc-ubuntu
    spec:
      domain:
        cpu:
          cores: 4
          model: host-passthrough
        memory:
          guest: "4G"
        devices:
          autoattachGraphicsDevice: true
          disks:
          - name: cdromiso
            bootOrder: 2
            cdrom:
              bus: sata
              readonly: true
          - name: bootdisk
            bootOrder: 1
            disk:
              bus: virtio
          - name: linuxutil
            cdrom:
              bus: sata
              readonly: true
          autoattachPodInterface: True
          interfaces:
          - name: default
            masquerade: {}
        machine:
          type: q35
        firmware:
          bootloader:
            efi:
              secureBoot: false
      terminationGracePeriodSeconds: 0
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        containerDisk:
          image: gar-registry.caas.intel.com/edgecloud-ecosystem-enabling/ubuntu22-iso-containerdisk
          imagePullPolicy: IfNotPresent
      - name: bootdisk
        persistentVolumeClaim:
          claimName: linuxbootdisk
      - name: linuxutil
        containerDisk:
          image: gar-registry.caas.intel.com/edgecloud-ecosystem-enabling/linuxutil-iso-containerdisk
          imagePullPolicy: IfNotPresent