apiVersion: v1
kind: Service
metadata:
  name: ssh
  namespace: default
spec:
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  selector:
    app/name: virtual-machine
  type: NodePort
