apiVersion: v1 
kind: PersistentVolume
metadata:
  name: pv-volume
  namespace: default
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/vm/images"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bootdisk
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
